swagger: "2.0"
info:
  description: "Minimal API"
  version: "1.0.0"
  title: "Minimal API"
paths:
  /greet:
    get:
      summary: "Greet the user"
      parameters:
        - name: "name"
          in: "query"
          required: true
          type: "string"
          description: "The name of the user to greet"
      responses:
        200:
          description: "A greeting message"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
